#!/usr/bin/env bash
rofi_command="rofi -theme $HOME/.config/rofi/config/notify.rasi"

notifies=$(dunstctl history |
  grep -A 2 "body\|summary" --no-group-separator |
  sed 's/\s:\s/<>/g' |
  sed "s/\\\\\"/'/g" |
  awk -F'<>' '
BEGIN {print("[ ");}
{
  if(NR % 3 == 0 && NR % 6 != 0 )
    print("{\"body\" : ",$2, ",");
  else if (NR % 6 == 0)
    print("\"head\" : ",$2,"},");
}
END {print("]")}' |
  awk '{ lines[NR] = $0 } END {
  # Modificar la penúltima línea
  # Imprimir todas las líneas
  for(i=1; i<=NR; i++)
  if (i == NR-1)
    print substr(lines[i],1,length(lines[i])-1)
  else
    print lines[i]
  }')
options=$(echo "$notifies" | jq -c '.[]' | while read notify; do
  body=$(echo "$notify" | jq -r '.body')
  head=$(echo "$notify" | jq -r '.head')
  echo "($head):\t$body"
done)
"$(echo -e "$options" | $rofi_command -p "Notify history " -dmenu -selected-row 0)"
