#!/usr/bin/env bash
screen_info=$(qtile cmd-obj -o screen -f info)
screen_index=$(printf "%s" $screen_info | jq -r '.index')
history_json="$(dunstctl history)"
history_items="$(printf '%s' "$history_json" | jq -r '.data[0][] | .appname.data , (.timestamp.data | tostring) , .summary.data, .body.data | gsub("[\\n]"; "\\n")')"
iter=0

IFS='
'
while
  read -r application_name
  read -r notification_timestamp
  read -r notification_summary
  read -r notification_body
do
  iter=$((iter + 1))

  # option=$(printf '<span foreground="%s"><b>%s</b> <small>(%s)</small>:</span> \n <i>%s</i>|\n' "$fg" "$notification_summary" "$application_name" "$notification_body")
  option=$(echo "(box :orientation \"v\" :space-evenly \"false\" :class \"notify-container\" :hexpand \"false\"\n\t(label :xalign 0.01 :class \"notify-title\" :justify \"left\" :wrap \"true\" :wrap-mode \"char\" :text \"$notification_summary ($application_name):\")\n\t(label :xalign 0.03 :class \"notify-content\" :wrap \"true\" :wrap-mode \"char\" :text \"$(echo $notification_body | sed 's/"/\\"/g')\")\n)\n")
  options="$options$option"
done <<EOF
$history_items
EOF
echo -e "(box :orientation \"v\" :spacing 0 :space-evenly \"false\"\n$options\n)"
