#!/usr/bin/env bash

case "$1" in
--menu)
  rofi -show drun -theme $HOME/.config/bspwm/scripts/Launcher.rasi
  ;;
--rice)
  RiceSelector
  ;;
--terminal)
  alacritty
  ;;
--floating)
  alacritty --hold --class FloatTermAlacritty -o window.dimensions.lines=22 window.dimensions.columns=90
  ;;
# --floating)
#   kitty --config $HOME/.config/kitty/kitty-float.conf --class FloatTerm,kitty -o initial_window_width=800 -o initial_window_height=400 -o remember_window_size=no
#   ;;
--update)
  alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
  ;;
--checkupdates)
  alacritty --hold --class Updating,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
  ;;
--TfileManager)
  alacritty --class FloatTermAlacritty -o window.dimensions.lines=22 window.dimensions.columns=90 -e $HOME/.local/bin/yazi
  ;;
# --TfileManager)
#   kitty --config $HOME/.config/kitty/kitty-float.conf --class FloatTerm,kitty -o initial_window_width=800 -o initial_window_height=400 -o remember_window_size=no -e yazi
#   ;;
--nvim)
  alacritty -e nvim
  ;;
--music)
  alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=18 window.dimensions.columns=67 -e ncmpcpp
  ;;
--fetch)
  alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
  ;;
# Apps
--filemanager)
  thunar
  ;;
--browser)
  firefox
  ;;
--editor)
  geany
  ;;
--telegram)
  telegram-desktop
  ;;
--whats)
  whatsapp-nativefier --disable-gpu
  ;;
--soundcontrol)
  pavucontrol
  ;;
# Eww Widgets
--powermenu)
  eww -c "$WIDGET_DIR" open --toggle powermenu
  ;;
--usercard)
  eww -c "$WIDGET_DIR" open --toggle launchermenu
  ;;
--player)
  eww -c "$WIDGET_DIR" open --toggle music
  ;;
--calendar)
  eww -c "$WIDGET_DIR" open --toggle date
  ;;
*)
  echo "Opción no válida"
  ;;
esac
