#!/usr/bin/env bash
rofi_command="rofi -theme $HOME/.config/rofi/config/powermenu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# Options
if [[ "$DIR" == "powermenus" ]]; then
  shutdown=""
  reboot=""
  lock=""
  suspend=""
  logout=""
  ddir="$HOME/.config/rofi/config"
else

  # For some reason the Icons are mess up I don't know why but to fix it uncomment section 2 and comment section 1 but if the section 1 icons are mess up uncomment section 2 and comment section 1

  # Buttons
  layout=$(cat $HOME/.config/rofi/config/powermenu.rasi | grep BUTTON | cut -d'=' -f2 | tr -d '[:blank:],*/')
  if [[ "$layout" == "TRUE" ]]; then
    # Section 1

    # shutdown=""
    # reboot=""
    # lock=""
    # suspend=""
    # logout=""
    # Section 2
    shutdown="󰐥"
    reboot="󰜉"
    lock="󰍁"
    suspend="󰒲"
    logout="󰍃 "

  else
    # Section 1
    shutdown=" Shutdown"
    reboot=" Restart"
    lock=" Lock"
    suspend=" Sleep"
    logout=" Logout"
    # Section 2
    #		shutdown="󰐥Shutdown"
    #		reboot="󰜉 Restart"
    #		lock="󰍁 Lock"
    #		suspend="󰒲Sleep"
    #		logout="󰍃 Logout"
  fi
  ddir="$HOME/.config/rofi/config"
fi

# Ask for confirmation
rdialog() {
  echo -e "\n󰜺" | rofi -dmenu -p "¿esta seguro?" -theme "$ddir/confirm.rasi"
}

# Variable passed to rofi
options="$lock\n$suspend\n$logout\n$reboot\n$shutdown"

chosen="$(echo -e "$options" | $rofi_command -p "UP - $uptime" -dmenu -selected-row 0)"
case $chosen in
$shutdown)
  ans=$(rdialog &)
  if [[ $ans == "" ]]; then
    systemctl poweroff
  else
    exit
  fi
  ;;
$reboot)
  ans=$(rdialog &)
  if [[ $ans == "" ]]; then
    systemctl reboot
  else
    exit
  fi
  ;;
$lock)
  sh $HOME/.local/bin/lock
  ;;
$suspend)
  ans=$(rdialog &)
  if [[ $ans == "" ]]; then
    mpc -q pause
    amixer set Master mute
    sh $HOME/.local/bin/lock
    systemctl suspend
  else
    exit
  fi
  ;;
$logout)
  ans=$(rdialog &)
  if [[ $ans == "" ]]; then
    pkill -9 -u $USER
  else
    exit
  fi
  ;;
esac
