#!/bin/bash

TEMP_IMAGE="/tmp/screen_locker.png"

magick "$(/bin/cat "$HOME"/.wallpaper)" -blur 5x5 "$TEMP_IMAGE"

# 3. Bloqueo de pantalla
if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
  swaylock -n -i "$TEMP_IMAGE" -s fill -e -u
  rm "$TEMP_IMAGE" # Limpieza manual recomendada en Wayland
else
  i3lock -n -i "$TEMP_IMAGE" -e -u
fi
