#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/config/center-menu.rasi"

commands="$(/bin/cat $HOME/.config/qtile/assets/rofi-theme.txt)"
chosse="$(echo -e "$commands" | $rofi_command -dmenu -i -p "󰔎 ")"

if [ "$chosse" != "" ]; then
  pkill dunst
  dunst -config $HOME/.config/qtile/themes/$chosse/dunstrc &
  notify-send "El tema a sido cambiado" "$chosse"
  echo "@import \"$chosse.rasi\"" >$HOME/.config/rofi/themes/default.rasi
  echo "include $chosse.conf" >$HOME/.config/kitty/themes/default.conf
  kill -SIGUSR1 $(pidof kitty)
  echo -e "{\n\t\"theme\": \"$chosse\"\n}" >$HOME/.config/qtile/config.json
  if [ -d $HOME/.mozilla/firefox/$(/bin/ls $HOME/.mozilla/firefox/ | grep -e '.default-release*$')/chrome ]; then
    echo "@import \"./themes/$chosse.css\";" >$HOME/.mozilla/firefox/$(/bin/ls $HOME/.mozilla/firefox/ | grep -e '.default-release*$')/chrome/theme.css
  fi
  images="$(xdg-user-dir PICTURES)/background"
  themes="themes/$(/bin/cat ~/.config/qtile/config.json | sed -n 's/^[[:space:]]*\"theme\":[[:space:]]*\"\([^;]*\)\".*$/\1/p')"

  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  case $chosse in
  "nord")
    feh --bg-fill "$images/$themes/wallhaven-2em38y_1920x1080.png"
    ;;
  "batman")
    feh --bg-fill "$images/$themes/wallhaven-01zjqg_1920x1080.png"
    ;;
  "catppuccin-mocha")
    feh --bg-fill "$images/$themes/wallhaven-1qkz23_1920x1080.png"
    ;;
  "catppuccin-latte")
    feh --bg-fill "$images/$themes/sky-cat.png"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
  "rose-pine-dawn")
    feh --bg-fill "$images/$themes/sky-cat.png"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
  esac
  qtile cmd-obj -o cmd -f restart

fi
