#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/config/center-menu.rasi"

commands="$(/bin/cat $HOME/.config/qtile/assets/rofi-theme.txt)"
chosse="$(echo -e "$commands" | $rofi_command -dmenu -i -p "󰔎 ")"

if [ "$chosse" != "" ]; then
  pkill dunst
  dunst -config $HOME/.config/qtile/themes/$chosse/dunstrc &
  notify-send "El tema a sido cambiado" "$chosse"
  echo "@import \"$chosse.rasi\"" >$HOME/.config/rofi/themes/default.rasi
  echo "@import \"themes/$chosse.scss\"" >$HOME/.config/qtile/assets/eww/colors.scss
  kill -SIGUSR1 $(pidof eww)
  echo "include $chosse.conf" >$HOME/.config/kitty/themes/default.conf
  kill -SIGUSR1 $(pidof kitty)
  if [ -f $HOME/.config/qtile/config.json ]; then
    echo -e $(jq --arg theme "$chosse" '.theme |= $theme' $HOME/.config/qtile/config.json) >$HOME/.config/qtile/config.json
  fi
  if [ -d $HOME/.mozilla/firefox/$(/bin/ls $HOME/.mozilla/firefox/ | grep -e '.default-release*$')/chrome ]; then
    echo "@import \"./themes/$chosse.css\";" >$HOME/.mozilla/firefox/$(/bin/ls $HOME/.mozilla/firefox/ | grep -e '.default-release*$')/chrome/theme.css
  fi
  images="$(xdg-user-dir PICTURES)/background"
  themes="themes/$(/bin/cat ~/.config/qtile/config.json | jq .theme | tr -d '"')"

  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  case $chosse in
  "nord")
    wallpaper="$images/$themes/wallhaven-2em38y_1920x1080.png"
    ;;
  "batman")
    wallpaper="$images/$themes/wallhaven-01zjqg_1920x1080.png"
    ;;
  "catppuccin-mocha")
    wallpaper="$images/$themes/wallhaven-1qkz23_1920x1080.png"
    ;;
  "catppuccin-latte")
    wallpaper="$images/$themes/sky-cat.png"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
  "rose-pine-dawn")
    wallpaper="$images/$themes/sky-cat.png"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
  esac
  if [ -f "$HOME"/.wallpaper ]; then
    echo "$wallpaper" >"$HOME"/.wallpaper
  else
    touch "$HOME"/.wallpaper
    echo "$wallpaper" >"$HOME"/.wallpaper
  fi
  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    swaybg -i "$wallpaper"
  else
    feh --bg-fill "$wallpaper"
  fi

  qtile cmd-obj -o cmd -f reload_config
fi
