#!/usr/bin/env bash

rofi_command="rofi -theme $HOME/.config/rofi/config/wallpaper.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

images="$(xdg-user-dir PICTURES)/background"
theme=$(jq -r '.theme' $HOME/.config/qtile/config.json)
themes="themes/$theme"
if [ -d "$images/$themes" ]; then
  chosse="$(for a in "$images/$themes"/*.png; do echo -en "$a\0icon\x1f$a\n"; done | $rofi_command -dmenu -selected-row 0 -p "UP - $uptime")"

else
  chosse="$(for a in $images/*.png; do echo -en "$a\0icon\x1f$a\n"; done | $rofi_command -dmenu -selected-row 0 -p "UP - $uptime")"
fi

if [ "$chosse" != "" ]; then
  if [ -f "$HOME"/.wallpaper ]; then
    echo "$chosse" >"$HOME"/.wallpaper
  else
    touch "$HOME"/.wallpaper
    echo "$chosse" >"$HOME"/.wallpaper
  fi

  if [ "$XDG_SESSION_TYPE" = "wayland" ]; then
    swaybg -i "$chosse"
  else
    feh --bg-fill "$chosse"
  fi

  notify-send "Wallpaper changed" "$chosse"
fi
