#!/usr/bin/env bash
icons_apps="$HOME/.icons/km"
rofi_conf="rofi -dmenu -selected-row 0"
theme="Selector de tema\0icon\x1f$icons_apps/theme.svg"
wallpaper="Selector de fondo\0icon\x1f$icons_apps/wallpaper.svg"
notify="Notificaciones\0icon\x1f$icons_apps/notification.svg"
clipcat="Portapapeles\0icon\x1f$icons_apps/clipboard.svg"
emojis="Emojis\0icon\x1f$icons_apps/emojis.svg"
application="Aplicaciones\0icon\x1f$icons_apps/app.svg"
performance="Modo de rendimiento\0icon\x1f$icons_apps/performance.svg"
zellij="Zellij\0icon\x1f$icons_apps/workspace.svg"
htop="Administrador de procesos\0icon\x1f$icons_apps/task_manager.svg"
update="Actualizar\0icon\x1f"$icons_apps"/update.svg"
ans=$(echo -en "$application\n$theme\n$wallpaper\n$notify\n$clipcat\n$emojis\n$performance\n$zellij\n$htop\n$update" | $rofi_conf -p "󰧾 ")
ans=$(echo "$ans" | sed -e 's/^[[\\0icon\x1f]]*//g')
screen=$(qtile cmd-obj -o screen -f info | jq .index)
case $ans in
"Aplicaciones")
  rofi -show drun
  ;;
"Selector de tema")
  theme-selector
  ;;
"Selector de fondo")
  wallpaper_selector
  ;;
"Notificaciones")
  notifyHistory
  eww -c "$CONFIG_EWW" open --toggle notify --screen "$screen"
  ;;
"Portapapeles")
  OpenApps --clipcat
  ;;
"Emojis")
  rofimoji --selector-args="-theme $CONFIG_ROFI/config/emoji-center-menu.rasi" --use-icons
  ;;
"Modo de rendimiento")
  powerprofile
  ;;
"Zellij")
  commandzellij
  ;;
"Administrador de procesos")
  OpenApps --htop
  ;;
"Actualizar")
  OpenApps --update
  ;;
esac
