#!/usr/bin/env bash

sessions_list=$(zellij list-sessions -n | awk '{print $1;}')
result=$(printf "%s\n" $sessions_list | rofi -dmenu -i -p " " -theme $CONFIG_ROFI/config/center-menu.rasi)
if [ "$result" != "" ]; then
  kitty sh -c "zellij attach $result"
fi
