#!/usr/bin/env bash

source "$HOME/.zshrc" 2>/dev/null

sessions_list=$(zellij list-sessions 2>/dev/null | awk '{gsub(/\x1b\[[0-9;]*[a-zA-Z]/, ""); print $1}')
result=$(echo -e "$sessions_list" | rofi -dmenu -i -p " " -theme "$CONFIG_ROFI"/config/center-menu.rasi)
if [ "$result" != "" ]; then
  kitty sh -c "zellij attach $result" &
fi
