#!/usr/bin/env bash

rofi_command="rofi -dmenu -theme $CONFIG_ROFI/config/center-menu.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

# images="$(xdg-user-dir PICTURES)/backgroud"
commands="$(/bin/cat $XDG_CONFIG_KM/commands.txt)"
chosse="$(echo -e "$commands" | $rofi_command -selected-row 0 -p "  ")"
