#!/usr/bin/env bash
screen_info=$(qtile cmd-obj -o screen -f info)
screen_index=$(printf "%s" $screen_info | jq -r '.index')
history_json="$(dunstctl history)"
history_items="$(printf '%s' "$history_json" | jq -r '.data[0][] | .appname.data , (.timestamp.data | tostring) , .summary.data, .body.data | gsub("[\\n]"; "\\n")')"
iter=0

IFS='
'
while
  read -r application_name
  read -r notification_timestamp
  read -r notification_summary
  read -r notification_body
do
  iter=$((iter + 1))

  clean_body=$(echo "$notification_body" | sed 's/"/\\"/g' | tr -d '\n')
  clean_summary=$(echo "$notification_summary" | sed 's/"/\\"/g')

  option="\t(box :orientation \"v\" :space-evenly false :class \"notify-container\" :hexpand false \n\t\t(label :xalign 0.01 :class \"notify-title\" :justify \"left\" :wrap true :wrap-mode \"char\" :text \"$clean_summary ($application_name):\") \n\t\t(label :xalign 0.03 :class \"notify-content\" :wrap true :wrap-mode \"char\" :text \"$clean_body\")\n)"
  options="$options $option"
done <<EOF
$history_items
EOF

echo -e "(box :orientation \"v\" :spacing 0 :space-evenly false $options)"
