#!/usr/bin/env bash

screen=$(qtile cmd-obj -o screen -f info | jq .index)

case "$1" in
--htop)
  kitty --config $CONFIG_KITTY/kitty-float.conf --class FloatTerm,kitty -o initial_window_width=800 -o initial_window_height=400 -o remember_window_size=no -e htop
  ;;
--notify)
  eww -c "$CONFIG_EWW" open --toggle notify --screen "$screen"
  ;;
--emoji)
  rofimoji --selector-args="-theme $CONFIG_ROFI/config/emoji-center-menu.rasi" --use-icons
  ;;
--screenlock)
  screenLocker
  ;;
--actions)
  actions
  ;;
--menu)
  rofi -show drun -theme $HOME/.config/bspwm/scripts/Launcher.rasi
  ;;
--clipcat)
  wl-clip-menu
  ;;
--rice)
  RiceSelector
  ;;
--terminal)
  alacritty
  ;;
--reloadSxhk)
  pkill -HUP swhkd
  notify-send "Reloading sxhkd"
  ;;
# --floating)
#   alacritty --hold --class FloatTermAlacritty -o window.dimensions.lines=22 window.dimensions.columns=90
#   ;;
--floating)
  kitty --config $CONFIG_KITTY/kitty-float.conf --class FloatTerm,kitty -o initial_window_width=800 -o initial_window_height=400 -o remember_window_size=no
  ;;
--update)
  alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=90 -e Updates --update-system
  ;;
--checkupdates)
  alacritty --hold --class Updating,Alacritty -o window.dimensions.lines=22 window.dimensions.columns=47 -e Updates --print-updates
  ;;
# --TfileManager)
#   alacritty --class FloatTermAlacritty -o window.dimensions.lines=22 window.dimensions.columns=90 -e $HOME/.local/bin/yazi
#   ;;
--TfileManager)
  kitty --config $CONFIG_KITTY/kitty-float.conf --class FloatTerm,kitty -o initial_window_width=800 -o initial_window_height=400 -o remember_window_size=no -e yazi
  ;;
--nvim)
  alacritty -e nvim
  ;;
--music)
  alacritty --class FloaTerm,Alacritty -o window.dimensions.lines=18 window.dimensions.columns=67 -e ncmpcpp
  ;;
--fetch)
  alacritty --hold --class FloaTerm,Alacritty -o window.dimensions.lines=26 window.dimensions.columns=40 -e ~/.local/bin/sysfetch
  ;;
# Apps
--filemanager)
  thunar
  ;;
--browser)
  firefox
  ;;
--editor)
  geany
  ;;
--telegram)
  telegram-desktop
  ;;
--whats)
  whatsapp-nativefier --disable-gpu
  ;;
--soundcontrol)
  pavucontrol
  ;;
# Eww Widgets
--helpKey)
  eww -c "$CONFIG_EWW" open --toggle cheatsheet --screen "$screen"
  ;;
--usercard)
  eww -c "$CONFIG_EWW" open --toggle launchermenu
  ;;
--player)
  eww -c "$CONFIG_EWW" open --toggle music
  ;;
--calendar)
  eww -c "$CONFIG_EWW" open --toggle date
  ;;
*)
  echo "Opción no válida"
  ;;
esac
