#!/usr/bin/env bash

rofi_command="rofi -theme $CONFIG_ROFI/config/center-menu.rasi"

list="$(powerprofilesctl list | awk '{if (NR == 1 || NR == 6 || NR == 10) print}' | sed 's/://g')"

selected="$(echo -e "$list" | $rofi_command -dmenu -p "󰓅 " | sed 's/[*]//g')"

powerprofilesctl set $selected
