#!/usr/bin/env bash

rofi_command="rofi -theme $CONFIG_ROFI/config/center-menu.rasi"

list="$(powerprofilesctl list | grep -E '^\*? +[a-z-]+:' | awk -F: '{print $1}' | tr -d '* ')"

selected="$(echo -e "$list" | $rofi_command -dmenu -p "󰓅 " | sed 's/[*]//g')"

powerprofilesctl set $selected
