#!/usr/bin/env bash

rofi_command="rofi -theme $CONFIG_ROFI/config/center-menu.rasi"

commands="$(/bin/cat $XDG_CONFIG_KM/rofi-theme.txt)"
chosse="$(echo -e "$commands" | $rofi_command -dmenu -i -p "󰔎 ")"

if [ "$chosse" != "" ]; then
  pkill dunst
  dunst -config $HOME/.config/qtile/themes/$chosse/dunstrc &
  notify-send "El tema a sido cambiado" "$chosse"
  echo "@import \"$chosse.rasi\"" >$CONFIG_ROFI/themes/default.rasi
  echo "@import \"themes/$chosse.scss\"" >$CONFIG_EWW/colors.scss
  kill -SIGUSR1 $(pidof eww)
  echo "include $chosse.conf" >$CONFIG_KITTY/themes/default.conf
  kill -SIGUSR1 $(pidof kitty)
  if [ -f $CONFIG_QTILE/config.json ]; then
    echo -e $(jq --arg theme "$chosse" '.theme |= $theme' $CONFIG_QTILE/config.json) >$CONFIG_QTILE/config.json
  fi
  if [ -d $HOME/.mozilla/firefox/$(/bin/ls $HOME/.mozilla/firefox/ | grep -e '.default-release*$')/chrome ]; then
    echo "@import \"./themes/$chosse.css\";" >$HOME/.mozilla/firefox/$(/bin/ls $HOME/.mozilla/firefox/ | grep -e '.default-release*$')/chrome/theme.css
  fi
  qtile cmd-obj -o cmd -f reload_config
  images="$(xdg-user-dir PICTURES)/background"
  themes="themes/$(/bin/cat $CONFIG_QTILE/config.json | jq .theme | tr -d '"')"

  gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'
  case $chosse in
  "nord")
    wallpaper="$images/$themes/wallhaven-2em38y_1920x1080.png"
    ;;
  "batman")
    wallpaper="$images/$themes/wallhaven-01zjqg_1920x1080.png"
    ;;
  "catppuccin-mocha")
    wallpaper="$images/$themes/wallhaven-1qkz23_1920x1080.png"
    ;;
  "catppuccin-latte")
    wallpaper="$images/$themes/sky-cat.png"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
  "rose-pine-dawn")
    wallpaper="$images/$themes/sky-cat.png"
    gsettings set org.gnome.desktop.interface color-scheme 'prefer-light'
    ;;
  esac
  if [ -f "$XDG_CONFIG_KM"/.wallpaper ]; then
    echo "$wallpaper" >"$XDG_CONFIG_KM"/.wallpaper
  else
    touch "$XDG_CONFIG_KM"/.wallpaper
    echo "$wallpaper" >"$XDG_CONFIG_KM"/.wallpaper
  fi

  swaybg -i "$wallpaper"

fi
