#!/usr/bin/env zsh
if command -v dnf >/dev/null 2>&1; then
## Aliases

local dnfprog="dnf"

command -v dnf5 > /dev/null && dnfprog=dnf5

alias dnfl="${dnfprog} list"                       # List packages
alias dnfli="${dnfprog} list installed"            # List installed packages
alias dnfgl="${dnfprog} grouplist"                 # List package groups
alias dnfmc="${dnfprog} makecache"                 # Generate metadata cache
alias dnfp="${dnfprog} info"                       # Show package information
alias dnfs="${dnfprog} search"                     # Search package

alias dnfu="sudo ${dnfprog} upgrade"               # Upgrade package
alias dnfi="sudo ${dnfprog} install"               # Install package
alias dnfgi="sudo ${dnfprog} groupinstall"         # Install package group
alias dnfr="sudo ${dnfprog} remove"                # Remove package
alias dnfgr="sudo ${dnfprog} groupremove"          # Remove package group
alias dnfc="sudo ${dnfprog} clean all"             # Clean cache
else
  echo "no se encontro dnf"
  exit 1
fi
echo -e "actualizando los packetes del sistema\n"
function error {
  echo -e "\n\n❌ Error: $1\n"
  exit 1
}
dnfu -y  || error "al actualizar los packetes del sistema dnf" &&\
brew update -y || error "al actualizar los packetes del sistema brew" &&\
brew upgrade -y || error "al actualizar los packetes del sistema brew"
echo "✅ actualizacion finalizada precione cualquier tecla para continuar"
read -n 1 -s

