#!/usr/bin/env bash

rofi_command="rofi -theme $CONFIG_ROFI/config/wallpaper.rasi"

uptime=$(uptime -p | sed -e 's/up //g')

images="$(xdg-user-dir PICTURES)/background"
theme=$(jq -r '.theme' $CONFIG_QTILE/config.json)
themes="themes/$theme"
if [ -d "$images/$themes" ]; then
  chosse="$(for a in "$images/$themes"/*.png; do echo -en "$a\0icon\x1f$a\n"; done | $rofi_command -dmenu -selected-row 0 -p "UP - $uptime")"

else
  chosse="$(for a in $images/*.png; do echo -en "$a\0icon\x1f$a\n"; done | $rofi_command -dmenu -selected-row 0 -p "UP - $uptime")"
fi

if [ "$chosse" != "" ]; then
  if [ -f "$XDG_CONFIG_KM"/.wallpaper ]; then
    echo "$chosse" >"$XDG_CONFIG_KM"/.wallpaper
  else
    touch "$XDG_CONFIG_KM"/.wallpaper
    echo "$chosse" >"$XDG_CONFIG_KM"/.wallpaper
  fi
  swaybg -i "$chosse"
  notify-send "Wallpaper changed" "$chosse"
fi
