[opener]
extract = [
	{ run = 'ouch decompress -y "%*"', desc = "Extract here with ouch", for = "windows" },
	{ run = 'ouch decompress -y "$@"', desc = "Extract here with ouch", for = "unix" },
]

[plugin]
prepend_previewers = [
  {url = "*.{md,markdown,txt}", run = "mdv-previewer"},
  # { url = "*.{md,markdown,rst,ipynb,json,csv}", run = "rich-preview" },
  { mime = "application/*zip",            run = "ouch" },
	{ mime = "application/x-tar",           run = "ouch" },
	{ mime = "application/x-bzip2",         run = "ouch" },
	{ mime = "application/x-7z-compressed", run = "ouch" },
	{ mime = "application/x-rar",           run = "ouch" },
  { mime = "application/x-xz",            run = "ouch" },
	{ mime = "application/xz",              run = "ouch" },

]
prepend_preloaders = [
  {url = "*.{md,markdown,txt}", run = "mdv-previewer"},
]

[mgr]
ratio = [0,2,6]
